### PR TITLE
Add option to use universal vs app scheme links when possible

### LINKED ISSUE #64: Use universal instead app scheme links
Universal links are generally safer and more reliable. It would be nice to have the option to use them instead of app schemes when possible.

### PR DESCRIPTION
**Pull request by mooshee**
# Description

Resolves #64

## How Has This Been Tested?
1. Supply a universal and native link in the AppMetadata
2. Toggle the `preferUniversalLinks` flag
3. Launch a wallet

### CODE REVIEW

**Comment by mooshee** [comment]
Not sure this works for all wallets at the moment. Started this PR as a conversation started to see the appetite for moving this direction. Most native SDKs (Coinbase, Phantom, SolFlare, to name a few) are going this route because it's more reliable, secure and a better user experience.

**Comment by bkrem** [comment]
Hey @mooshee, thank you for jumping in with the contribution 💪 Wanted to note that @llbartekll is OOO Thu/Fri, we'll get back to you here on Monday when he's back 🙏

**Comment by chichkanov** [comment]
hey guys, any update on this?

**Comment by llbartekll** [comment]
hey @mooshee, thank you for your contribution.
> it's more reliable, secure and a better user experience.

I couldn't agree more, but the problem is that historically, universal linking hasn't worked very well due to flawed integrations. There have been many cases where users ended up in the App Store or Safari instead of the intended destination. When a dApp connects to a single wallet, it’s simple to rely on. However, in the case of W3M, where you have hundreds of wallets, it's not that simple. Regardless, we will definitely provide an alternative soon.

**Comment by mooshee** [comment]
Ostensibly, all dapps and wallets should have their universal links defined in the wallet connect registry.  It would make sense to allow us to override the registry with the local metadata configuration.

Good to know you're working on it. Thanks for the update!

**Pull request closed without merging**
